[package]
name = "spake2"
version = "0.1.0"
authors = ["Brian Warner <warner@lothar.com>"]

[dependencies]
#rust-crypto = "^0.2"
curve25519-dalek = "0.8.0"
rand = "0.3.0"
sha2 = "0.4.0"

[dev-dependencies]
num-bigint = "0.1"
hex = "0.2"
