[package]
name = "srp"
version = "0.1.1"
authors = ["RustCrypto Developers"]
license = "MIT/Apache-2.0"
description = "Secure Remote Password (SRP) protocol implementation"
documentation = "https://docs.rs/srp"
repository = "https://github.com/RustCrypto/SRP"
keywords = ["crypto", "pake", "authentication"]
categories = ["cryptography", "authentication"]

[dependencies]
num = "0.1"
generic-array = "0.8"
rand = "0.3"
digest = "0.6"

[dev-dependencies]
sha2 = "0.6"

[badges]
travis-ci = { repository = "RustCrypto/SRP" }
