[package]
name = "srp"
version = "0.1.0"
authors = ["RustCrypto Developers"]
license = "MIT/Apache-2.0"
description = "Secure Remote Password (SRP) protocol implementation"
documentation = "https://docs.rs/srp"
repository = "https://github.com/RustCrypto/SRP"
keywords = ["crypto", "pake", "authentication"]
categories = ["cryptography", "authentication"]

[dependencies]
num = "*"
generic-array = "*"
rand = "0.3"
digest = "*"

[dev-dependencies]
sha2 = "*"

[badges]
travis-ci = { repository = "RustCrypto/SRP" }
