[package]
name = "spake2"
version = "0.1.0"
authors = ["Brian Warner <warner@lothar.com>"]

[dependencies]
#rust-crypto = "^0.2"
curve25519-dalek = "0.9.0"
rand = "0.3.0"
#sha2 = "0.4.0"
rust-crypto = "0.2"
num-bigint = "0.1"
hex = "0.2"

[dev-dependencies]
hex = "0.2"
